apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: my-node-app
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
        #nodePort: 30002
